name: build

on: [push, pull_request]

env:
  SLN:  CsvLINQPadDriver.sln
  SLN5: CsvLINQPadDriver.LINQPad5.sln
  SLN_CONFIG: Release
  BIN_POSTFIX: .Bin
  RETENTION_DAYS: 1

jobs:
  build:
    runs-on: windows-latest

    steps:

    # Set up

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: |
          8.0.x

    # Check out

    - name: Check out ${{env.SLN}}
      uses: actions/checkout@v4.1.1

    # LINQPad 8/7/6

    - name: Restore ${{env.SLN}}
      run: dotnet restore ${{env.SLN}}

    - name: Build ${{env.SLN}} ${{env.SLN_CONFIG}}
      run: dotnet build ${{env.SLN}} --configuration ${{env.SLN_CONFIG}} --no-restore -p:GITHUB_ACTIONS=true

    - name: Test ${{env.SLN}} ${{env.SLN_CONFIG}}
      run: dotnet test ${{env.SLN}} --configuration ${{env.SLN_CONFIG}} --no-build --verbosity normal

    # LINQPad 5

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.3.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Restore ${{env.SLN5}}
      run: nuget restore ${{env.SLN5}}

    - name: Build ${{env.SLN5}} ${{env.SLN_CONFIG}}
      run: msbuild ${{env.SLN5}} /p:Configuration=${{env.SLN_CONFIG}}

    # Create LPX

    - name: Build LPX
      run: Deploy/buildlpx.cmd

    # Upload artifacts

    - name: Publish ${{env.SLN}} ${{env.SLN_CONFIG}}, ${{env.SLN5}} ${{env.SLN_CONFIG}}
      uses: actions/upload-artifact@v4.3.0
      with:
        name: CsvLINQPadDriver${{env.BIN_POSTFIX}}
        path: |
          bin/${{env.SLN_CONFIG}}/CsvLINQPadDriver.*.*nupkg
          Deploy/*.lpx
          Deploy/*.lpx?
        retention-days: ${{env.RETENTION_DAYS}}
